# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

# Pods for MoviesChecker 
def shared_pods
  pod 'Alamofire', '~> 4.5'
  pod 'ObjectMapper', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'Kingfisher', '~> 4.0'
end

target 'MoviesChecker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  shared_pods

  target 'MoviesCheckerTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

  target 'MoviesCheckerUITests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

end
